# 设置启动的环境
spring:
  profiles:
    active: dev
#公共配置一样都写在这里
#server:
#  port: 8080

---
# 线上环境
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.235.114.165:3306/db_user?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root@qing#429
  config:
    activate:
      on-profile: pro
server:
  port: 8080

---
# 开发环境
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.101:3306/db_user?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Xhp123456.
  config:
    activate:
      on-profile: dev
server:
  port: 8081


# 打包
# 1.mvn clean
# 2.mvn package 打包jar，文件在target目录下
# 3.运行jar
# java -jar  xxx.jar
# java -jar xxx.jar --spring.profiles.active=pro // 使用pro环境运行
# 还可以在jar路径下放置application.yml文件进行加载

